# Data from [local.direct.gov.uk/Data/](http://local.direct.gov.uk/Data/)
URL='http://local.direct.gov.uk/Data/local_authority_contact_details.csv'

local_authority_contact_details.csv:
	curl -qs $(URL) > $@
