# Data from OS, download here: https://www.ordnancesurvey.co.uk/opendatadownload/products.html#OPNAME

# mkdir cache
# cd cache
# unzip opname_csv_gb.zip
# cd ..
# mix deps.get
# iex -S mix run -e "OrdinanceSurvey.write_all"
