# Local Land and Property custodian codes found in the National Address Gazetteer and OS AddressBase™
URL='https://www.ordnancesurvey.co.uk/docs/product-schemas/addressbase-products-local-custodian-codes.zip'
ZIP='addressbase-products-local-custodian-codes.zip'

# hard to script extracting codes from the .docx document
$(ZIP):
	curl -qs $(URL) > $@
